ComputeDamage=true
ComputeBuff=true
ComputeCast=true
ComputeMechanics=true
ComputeDamageModifiers=true
ParsePhases=true
ParseCombatReplay=false
SaveOutJSON=true
SaveAtOut=false
OutLocation=./20260718-165658.zevtc/output
